AllCops:
  Exclude:
    - '../db/**/*'
    - '../config/**/*'

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/Documentation:
  Exclude:
    - '../app/controllers/**/*'
    - '../app/models/**/*'
